### ISSUE TITLE
get_graph_feature adds tensors on two different devices

### ISSUE THREAD

**Issue by nazMahmoud** [MohamedAfham/CrossPoint#1]
Thank you for your contributions. Very interesting work!. I have two GPUs and I'm trying to run crosspoint pre-training for classification using:

`python train_crosspoint.py --model dgcnn --epochs 100 --lr 0.001 --exp_name crosspoint_dgcnn_cls --batch_size 20 --print_freq 200 --k 15`

And i'm getting the following error:

``` 
Traceback (most recent call last):
  File "train_crosspoint.py", line 258, in <module>
    train(args, io)
  File "train_crosspoint.py", line 100, in train
    _, point_feats, _ = point_model(data)
  File "/home/nas/anaconda3/envs/crosspoint/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nas/Desktop/CrossPoint/models/dgcnn.py", line 95, in forward
    x = get_graph_feature(x, k=self.k)
  File "/home/nas/Desktop/CrossPoint/models/dgcnn.py", line 31, in get_graph_feature
    idx = idx + idx_base
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! 
```

Is there a reason for hardcoding cuda device to 1 here: [https://github.com/MohamedAfham/CrossPoint/blob/440e3bdf1656014eb4284786a6b2bcdf83e8df30/models/dgcnn.py#L27](url)

**Comment by MohamedAfham** [comment]
Hi, 

You can change the device as per your GPU availability. I'll update the code soon, but you can also define yourself.

Thanks.

**Comment by ZiyangW2000** [comment]
hi, will you update these issue?
